---
title: "DRC travel volume"
format: html
editor: visual
code-fold: true
---

## Travel volume from DRC to Canada

```{r}
knitr::opts_chunk$set(
  warning = FALSE, message = FALSE, error = FALSE, 
  fig.height = 9, fig.width = 12
  )
```

You can add options to executable code like this

```{r}
## load libraries
#library(terra)
library(tidyverse)
#library(rnaturalearth)
#library(sf)
#library(tidyterra)
#library(exactextractr)
#library(airportr)
library(patchwork)
library(here)
library(kableExtra)
library(knitr)

options(scipen = 999)

## set directory
#my_path <- Sys.getenv(x = "HOME")
#my_path <- str_replace(my_path, "Documents", "data/gis/countries/drc")

## load functions
source(here("code", "functions.R"))
```

```{r}
## load IATA travel volumes for past 24 months
filepath <- paste(save_path_rad, "drc_arrivals.rds", sep = "/")
drc_arrivals <- readRDS(filepath)
```

```{r}
## aggregate to monthly data
drc_monthly <- drc_arrivals |> 
  group_by(year, month, ym, date) |> 
  summarise(volume = sum(npass))

## flag months of interest
drc_monthly <- drc_monthly |> 
  mutate(
    period = if_else(month == "09" | month == "10", 1, 0)
  )
```

```{r, fig.height=6, fig.width=9}
## fill palette
my_fills <- scico::scico(2, palette = "lipari", begin = 0.2, end = 0.8)

## plot
drc_monthly |> 
  ggplot(aes(x = date, y = volume, fill = factor(period))) +
  geom_col() +
  scale_fill_manual(values = my_fills) +
  scale_x_date(date_breaks = "2 months" , date_labels = "%b-%y") +
  scale_y_continuous(breaks = seq(0, 1600, 200)) +
  labs(
    x = "Month",
    y = "Travel volume"
  ) +
  theme_minimal() +
  theme(
    legend.position = "none",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 45)
  )
```

```{r}
drc_monthly |> 
  select(year, month, volume) |> 
  kable() 
```

```{r}
## travel volume by source airport
drc_monthly_airport <- drc_arrivals |> 
  group_by(orig, year, month, ym, date) |> 
  summarise(volume = sum(npass))

drc_monthly_airport |> 
  pivot_wider(id_cols = c(ym, year ,month, date), names_from = orig, values_from = volume)
```
